### ISSUE TITLE
Add mongo seeds for cards in development mode

### ISSUE THREAD

**Issue by lucasmedeiros** [alvesmatheus/clow-cards#18]
I ran the project in development mode in my local machine, and I noticed that no cards were registered (of course, I ran it in my local instance of MongoDB). I think that, in the future, you can put some cards in a seed just to make development experience easier. For example, run a single command like `yarn seed` and it would automatically create some cards on the database.

**PS**: Implement seeds in MongoDB can be a little tough, so I recommend you to follow [this tutorial](https://medium.com/@pkosiec/seeding-mongodb-database-the-right-way-32a8a0e75490) if you're going to do it.

What do you think about it?

**Comment by alvesmatheus** [comment]
I completely agree. This is one of the features that I intend to implement as soon as I've finished the prioritary ones. Indeed, I had looked for ways to quickly produce the Clow Cards collection, but none of the tools that I've found seemed very appealing.

This tutorial will be very useful, thanks! 🥰
