### ISSUE TITLE
Melhorar o README.md

### ISSUE THREAD

**Issue by matheusgr** [alvesmatheus/clow-cards#5]
Tentar descrever melhor:

- [x] O projeto (funcionalidades e telas)
- [x] A tecnologia utilizada
- [x] Como executar

Lembra, a idéia do projeto é fazer parte do teu portfolio profissional :)

**Comment by alvesmatheus** [comment]
@matheusgr Adicionei os tópicos que você indicou sobre o `README.md`. Ainda pretendo dar uma melhorada nele à medida que for avançando no desenvolvimento, mas acho que a versão atual já dá pra ter uma "visão geral" do que vai ser o projeto.

Estou fechando essa *issue*, mas qualquer melhoria que esteja faltando, só comentar que reabro ela. :mage_man:
